-- local dictionary_root = vim.fn.stdpath("config") .. "/spell/"
-- vim.lsp.set_log_level(vim.log.levels.DEBUG)
--
-- return {
--   settings = {
--     ltex = {
--       dictionary = {
--         ["en-US"] = { ":" .. dictionary_root .. "common_terms.txt" }
--       }
--     }
--   }
-- }
return false
